### ISSUE TITLE
Jamming Bluetooth

### ISSUE THREAD

**Issue by menroka** [hackgnar/pyubertooth#9]
Hello!
I'm currently working on my Bachelor thesis regarding attacks on Bluetooth. I would like to use this library to achieve that, but sadly some commands don't seem to be implemented.
Specifically cmd_set_bdaddr, cmd_start_hopping and cmd_set_clock are needed to synchronize the devices.
I have yet to find any kind of documentation regarding the HCI of the Ubertooth One.
I am getting the raw data and using your BtbbPacket, I can determine whether a valid packet has been received and Im also reading out the clock via cmd_get_clock, however would like to also get the raw data following the LAP (I need the full Header).
I would be willing to implement that myself, however lacking documentation I dont know, what to send to the ctrl_transfer.
Feel free to let me know, what you think about this approach.

**Comment by dolice** [comment]
How to encoded my .dump file

**Comment by dolice** [comment]
Hallo,
How to encoded my .dump file

**Comment by hackgnar** [comment]
These features our out of the scope of this project. All of the features in this project are for reading and converting the output of an ubertooth.  There are currently no features to interact with ubertooth or to send data from an ubertooth
